# Project configuration
project_id = "uxycuaydoxccvoimogah"

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.n8n-proxy]
verify_jwt = false

[functions.store-video]
verify_jwt = false

[functions.video-timeout-check]
verify_jwt = false